### ISSUE TITLE
pandoc error 4compatibility.woff2: withBinaryFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by ire1990** [rstudio/fontawesome#100] opened 2022-11-17 16:29 UTC
Hi,

I am trying to knit an Rmarkdown file but I get this error: 
`pandoc: /home/irene/R/x86_64-pc-linux-gnu-library/4.2/fontawesome/fontawesome/css/../webfonts/fa-v4compatibility.woff2: withBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1`

I really dont understand what the package is missing, do you have any solutions? Thanks!

**Comment by raymondben** [comment] 2022-11-21 02:49
Is a duplicate of #99, I am also seeing the same thing. The relevant woff2 files were removed in https://github.com/rstudio/fontawesome/commit/230e7420249ce07b2eb1d22d8d0868ef5133955e

**Closed** 2023-01-24 18:10 UTC
